# Generated by Django 2.0.4 on 2018-04-11 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migrator_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backlog_issues',
            old_name='backlog_id',
            new_name='backlog',
        ),
    ]
