# Generated by Django 2.0.4 on 2018-04-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrator_app', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlog',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='source_repo',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
