# Generated by Django 2.0.4 on 2018-04-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrator_app', '0005_auto_20180427_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
